import os
from dotenv import load_dotenv
load_dotenv()

ESOCIAL_TP_AMB= os.getenv("ESOCIAL_TP_AMB")
ESOCIAL_PROC_EMI= os.getenv("ESOCIAL_PROC_EMI")
ESOCIAL_VER_PROC= os.getenv("ESOCIAL_VER_PROC")

ESOCIAL_TP_INSC= os.getenv("ESOCIAL_TP_INSC")
ESOCIAL_NR_INSC= os.getenv("ESOCIAL_NR_INSC")
ESOCIAL_CERT_PATH=os.getenv("ESOCIAL_CERT_PATH")
ESOCIAL_CERT_PASSWORD=os.getenv("ESOCIAL_CERT_PASSWORD")

URL_ENVIO = os.getenv("URL_ENVIO")


SOAP_ENV= os.getenv("SOAP_ENV")

SOAP_ACTION= os.getenv("SOAP_ACTION")

ESOCIAL_WS_NAMESPACE= os.getenv("ESOCIAL_WS_NAMESPACE")